// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCare.Infrastructure.Data;


#nullable disable

namespace PetCare.Migrations
{
    [DbContext(typeof(PetsDbContext))]
    [Migration("20260514165254_AddPetStateTable")]
    partial class AddPetStateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetCare.Domain.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppoinmentDate")
                        .HasColumnType("date")
                        .HasColumnName("appoinment_date");

                    b.Property<byte[]>("CreateAt")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("create_at");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.HasKey("Id")
                        .HasName("PK__appointm__3213E83F7AACF5C9");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StateId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("owner_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("PK__owners__3213E83FD227B16C");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pet_name");

                    b.Property<int?>("PetStateId")
                        .HasColumnType("int")
                        .HasColumnName("pet_state_id");

                    b.Property<int>("SpecieId")
                        .HasColumnType("int")
                        .HasColumnName("specie_id");

                    b.HasKey("Id")
                        .HasName("PK__pets__3213E83FB644E679");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetStateId");

                    b.HasIndex("SpecieId");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Models.PetState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("state_name");

                    b.HasKey("Id");

                    b.ToTable("pet_states", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("CreateAt")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("create_at");

                    b.Property<string>("SpecieName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("specie_name");

                    b.HasKey("Id")
                        .HasName("PK__species__3213E83FAABCB7CE");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Models.State", b =>
                {
                    b.Property<int>("IdState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_state");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdState"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("state_name");

                    b.HasKey("IdState")
                        .HasName("PK__states__12FD6C4943565E84");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Models.Appointment", b =>
                {
                    b.HasOne("PetCare.Domain.Models.Owner", "Owner")
                        .WithMany("Appointments")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__appointme__owner__33D4B598");

                    b.HasOne("PetCare.Domain.Models.State", "State")
                        .WithMany("Appointments")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK__appointme__state__32E0915F");

                    b.Navigation("Owner");

                    b.Navigation("State");
                });

            modelBuilder.Entity("PetCare.Domain.Models.Pet", b =>
                {
                    b.HasOne("PetCare.Domain.Models.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__pets__owner_id__2B3F6F97");

                    b.HasOne("PetCare.Domain.Models.PetState", "PetState")
                        .WithMany("Pets")
                        .HasForeignKey("PetStateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__pets__pet_state_id");

                    b.HasOne("PetCare.Domain.Models.Species", "Specie")
                        .WithMany("Pets")
                        .HasForeignKey("SpecieId")
                        .IsRequired()
                        .HasConstraintName("FK__pets__specie_id__2A4B4B5E");

                    b.Navigation("Owner");

                    b.Navigation("PetState");

                    b.Navigation("Specie");
                });

            modelBuilder.Entity("PetCare.Domain.Models.Owner", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCare.Domain.Models.PetState", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCare.Domain.Models.Species", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCare.Domain.Models.State", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
